<?php

return [
    'header' => "ប្រវត្តិសាកលវិទ្យាល័យ ប៊ែលធី អន្តរជាតិ",

    'description' => '

<p style=\'margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;text-indent:18.0pt;line-height:normal;\'><span style=\'font-size:16px;font-family:"Khmer OS Battambang";\'>សាកលវិទ្យាល័យ ប៊ែលធី អន្តរជាតិ គឺជាគ្រឹះស្ថានអប់រំឧត្តមសិក្សាឯកជនមួយ ដែលបានចាប់បដិសន្ធិឡើងនៅថ្ងៃទី៤ ខែសីហា ឆ្នាំ២០០៥ដោយផ្តើមចេញពីវិទ្យាស្ថាន ប៊ែលធី &nbsp; អន្តរជាតិ &nbsp;និងបានអភិវឌ្ឍទៅជាសាកលវិទ្យាល័យ ប៊ែលធី &nbsp;អន្តរជាតិ &nbsp;នៅថ្ងៃទី៦ &nbsp; ខែកញ្ញា &nbsp; ឆ្នាំ២០១២។សាកលវិទ្យាល័យប៊ែលធី អន្តរជាតិ ត្រូវបានសម្ពោធដាក់ឱ្យប្រើប្រាស់ជាផ្លូវការ នៅថ្ងៃទី២១ខែសីហា ឆ្នាំ២០១៤ ក្រោមអធិបតីភាពដ៏ខ្ពង់ខ្ពស់&nbsp;</span><span style=\'font-size:16px;font-family:"Khmer OS Muol Light";\'>សម្តេចអគ្គមហាសេនាបតីតេជោ ហ៊ុន សែន</span><span style=\'font-size:16px;font-family:"Khmer OS Battambang";\'>&nbsp;នាយករដ្ឋមន្ត្រី នៃព្រះរាជាណាចក្រកម្ពុជា។&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></p>
<p style=\'margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;text-indent:18.0pt;line-height:normal;\'><span style=\'font-size:16px;font-family:"Khmer OS Battambang";\'>សាកលវិទ្យាល័យ មានឈ្មោះពេញជាភាសាខ្មែរ&nbsp;</span><span style=\'font-size:16px;font-family:"Khmer OS Muol Light";\'>&ldquo;សាកលវិទ្យា-ល័យ ប៊ែលធី អន្តរជាតិ&rdquo;</span><span style=\'font-size:16px;font-family:"Khmer OS Battambang";\'>&nbsp; &nbsp;និងជាភាសាអង់គ្លេស &nbsp;&nbsp;</span><strong><span style=\'font-size:16px;font-family:"Calibri Light",sans-serif;\'>&ldquo;</span></strong><strong><span style=\'font-size:16px;font-family:"Calibri Light",sans-serif;\'>BELTEI INTERNATIONAL &nbsp;UNIVERSITY&rdquo;&nbsp;</span></strong><span style=\'font-size:16px;font-family:"Khmer OS Battambang";\'>&nbsp;ហើយឈ្មោះ&nbsp;</span><strong><span style=\'font-size:16px;font-family:"Calibri Light",sans-serif;\'>&ldquo;</span></strong><strong><span style=\'font-size:16px;font-family:"Calibri Light",sans-serif;\'>BELTEI&rdquo;</span></strong><span style=\'font-size:16px;font-family:"Khmer OS Battambang";\'>&nbsp; នេះផ្គុំទ្បើងដោយ ៦មុខជំនាញធំៗដូចជា&nbsp;</span><strong><span style=\'font-size:16px;font-family:"Calibri Light",sans-serif;\'>&ldquo;</span></strong><strong><span style=\'font-size:16px;font-family:"Calibri Light",sans-serif;\'>BEL&rdquo;</span></strong><span style=\'font-size:16px;font-family:"Khmer OS Battambang";\'>&nbsp;មកពីពាក្យ&nbsp;</span><strong><span style=\'font-size:16px;font-family:"Calibri Light",sans-serif;\'>Business, Economics, Law</span></strong><strong><span style="font-size:16px;">&nbsp;</span></strong><span style=\'font-size:16px;font-family:"Khmer OS Battambang";\'>&nbsp;និង &nbsp;&nbsp;</span><strong><span style=\'font-size:16px;font-family:"Calibri Light",sans-serif;\'>&ldquo;</span></strong><strong><span style=\'font-size:16px;font-family:"Calibri Light",sans-serif;\'>TEI&rdquo;</span></strong><span style=\'font-size:16px;font-family:"Khmer OS Battambang";\'>&nbsp; &nbsp;មកពីពាក្យ &nbsp;Tourism, &nbsp;English, Information Technology ។</span></p>
<p style=\'margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;text-indent:21.3pt;line-height:normal;\'><span style=\'font-size:16px;font-family:"Khmer OS Muol Light";\'>ឯកឧត្តមបណ្ឌិត លី ឆេង</span><span style=\'font-size:16px;font-family:"Khmer OS Battambang";\'>&nbsp;បច្ចុប្បន្នជាតំណាងរាស្ត្រមណ្ឌលរាជធានីភ្នំពេញ ជាអគ្គនាយក ប៊ែលធីគ្រុប និងជាប្រធានក្រុមប្រឹក្សាភិបាល សាកលវិទ្យាល័យ ប៊ែលធី អន្តរជាតិ គឺជាស្ថាបនិកតែម្នាក់គត់ ដែលបានវិនិយោគទុនក្នុងការបង្កើត និងសាងសង់អគារសាកលវិទ្យាល័យ ប៊ែលធី អន្តរជាតិ ទាំងអស់នេះ។</span></p>
<p style=\'margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;text-indent:21.3pt;line-height:normal;\'><span style=\'font-size:16px;font-family:"Khmer OS Battambang";\'>បច្ចុប្បន្ន សាកលវិទ្យាល័យមាន ២ទីតាំង នៅរាជធានីភ្នំពេញ ដែលកំពុងដំណើរការកម្មវិធី២ធំៗ (កម្មវិធីសិក្សាជា ភាសាជាតិ និងកម្មវិធីសិក្សា អន្តរជាតិ) មាន ១៣មហាវិទ្យាល័យ និង ៤៥ជំនាញ៖</span></p>
<p style=\'margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:normal;\'><span style=\'font-size:16px;font-family:"Khmer OS Muol Light";\'>- សាកលវិទ្យាល័យ ប៊ែលធី អន្តរជាតិ ទីតាំងទី ១ ទួលស្លែង</span><span style=\'font-size:16px;font-family:"Khmer OS Battambang";\'>៖ អគារ២១ ផ្លូវ៣៦០ សង្កាត់បឹងកេងកង៣ ខណ្ឌបឹងកេងកង រាជធានីភ្នំពេញ (ខាងត្បូងសារមន្ទីរទួលស្លែង១០០ម៉ែត្រ) អគារមានកម្ពស់១៥ជាន់ស្មើនឹង១១០បន្ទប់ មានសាលសហសិក្សា១ ចំណុះ១៥០នាក់ និងសាលសន្និសីទ១ ចំណុះ៧០០នាក់ មានអាហារដ្ឋាន១កន្លែង បណ្ណាល័យ១ និងចំណតយានយន្ត២ជាន់។&nbsp;</span></p>
<p style=\'margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;text-indent:7.1pt;line-height:normal;\'><span style=\'font-size:16px;font-family:"Khmer OS Muol Light";\'>- សាកលវិទ្យាល័យ ប៊ែលធី អន្តរជាតិ ទីតាំងទី ២ ស្ពានអាកាស ចោមចៅ៖</span><span style=\'font-size:16px;font-family:"Khmer OS Battambang";\'>&nbsp;អគារ១៥១ ផ្លូវជាតិលេខ៣ សង្កាត់ចោមចៅទី២ ខណ្ឌពោធិ៍សែនជ័យ រាជធានីភ្នំពេញ (ចម្ងាយប្រហែល ៥០០ម៉ែត្រ ពីស្ពានអាកាសចោមចៅ) &nbsp;អគារកម្ពស់៩ជាន់ ស្មើនឹង១៤២បន្ទប់ មានសាលសហសិក្សា១ចំណុះ១៥០នាក់ សាលមហោស្រព១ ចំណុះ៨០០នាក់ និងសាលសន្និសីទ១ ចំណុះ១</span><span style=\'font-size:16px;font-family:"Khmer OS Battambang";\'>,២០០នាក់ មានអាហារដ្ឋាន១កន្លែង បណ្ណាល័យ១ មានអគារអន្តេវាសិកដ្ឋាន១ ខ្នង ស្មើនឹង៦៥បន្ទប់មានគ្រែចំនួន១៣០ និងមានចំណតយានយន្តជាង១០,០០០ ម៉ែត្រការ៉េ។</span></p>

    
    ',
];
