@extends('web.client.school.layout.app')


@section('content')
    {!! trans('school/outstanding-student/city.table', [
        'image_1' => asset('asset/img/school/outstanding-student/city/cao_yinhhveng.png'),
        'image_2' => asset('asset/img/school/outstanding-student/city/chan_dara_mony.png'),
        'image_3' => asset('asset/img/school/outstanding-student/city/sea_sopor.png'),
        'image_4' => asset('asset/img/school/outstanding-student/city/tea_bunmeng.png'),
        'image_5' => asset('asset/img/school/outstanding-student/city/sao_sovannraksa.png'),
        'image_6' => asset('asset/img/school/outstanding-student/city/yahat_khhunarak.png'),
        'image_7' => asset('asset/img/school/outstanding-student/city/meng_chanheng.png'),
        'image_8' => asset('asset/img/school/outstanding-student/city/khhut_tithmariya.png'),
        'image_9' => asset('asset/img/school/outstanding-student/city/em_sireyputh.png'),
        'image_10' => asset('asset/img/school/outstanding-student/city/keo_piseth1.png'),
        'image_11' => asset('asset/img/school/outstanding-student/city/pen_potin.png'),
        'image_12' => asset('asset/img/school/outstanding-student/city/hy_socheat1.png'),
        'image_13' => asset('asset/img/school/outstanding-student/city/teang_sokyou.png'),
        'image_14' => asset('asset/img/school/outstanding-student/city/you_menghuy.png'),
        'image_15' => asset('asset/img/school/outstanding-student/city/kim_guechpor1.png'),
        'image_16' => asset('asset/img/school/outstanding-student/city/ly_sengchhay1.png'),
        'image_17' => asset('asset/img/school/outstanding-student/city/seang_kongmonyrotanakdom.png'),
        'image_18' => asset('asset/img/school/outstanding-student/city/norn_samnagmony.png'),
        'image_19' => asset('asset/img/school/outstanding-student/city/tea_hongsan.png'),
        'image_20' => asset('asset/img/school/outstanding-student/city/tea_bunmeng.png'),
        'image_21' => asset('asset/img/school/outstanding-student/city/ly_sengchhay.png'),
        'image_22' => asset('asset/img/school/outstanding-student/city/keo_piseth.png'),
        'image_23' => asset('asset/img/school/outstanding-student/city/kim_guechpor.png'),
        'image_24' => asset('asset/img/school/outstanding-student/city/em_sereyputh.png'),
        'image_25' => asset('asset/img/school/outstanding-student/city/hy_socheat.png'),
        'image_26' => asset('asset/img/school/outstanding-student/city/seang_kongmonyoudomratnak.png'),
        'image_27' => asset('asset/img/school/outstanding-student/city/dan_hangsing.png'),
        'image_28' => asset('asset/img/school/outstanding-student/city/ly_sokhom.png'),
        'image_29' => asset('asset/img/school/outstanding-student/city/sam_sereyvathana.png'),
        'image_30' => asset('asset/img/school/outstanding-student/city/thou_rennich.png'),
        'image_31' => asset('asset/img/school/outstanding-student/city/hout_sengkea.png'),
        'image_32' => asset('asset/img/school/outstanding-student/city/ear_ailoung.png'),
        'image_33' => asset('asset/img/school/outstanding-student/city/im_rachna.png'),
        'image_34' => asset('asset/img/school/outstanding-student/city/kheng_chanbopha.png'),
        'image_35' => asset('asset/img/school/outstanding-student/city/chea_lykun.png'),
        'image_36' => asset('asset/img/school/outstanding-student/city/kruy_kimty.png'),
        'image_37' => asset('asset/img/school/outstanding-student/city/tep_tidavorleak.png'),
        'image_38' => asset('asset/img/school/outstanding-student/city/sok_porhong.png'),
        'image_39' => asset('asset/img/school/outstanding-student/city/tep_voucheng.png'),
        'image_40' => asset('asset/img/school/outstanding-student/city/ka_vatana.png'),
        'image_41' => asset('asset/img/school/outstanding-student/city/sang_rachana.png'),
        'image_42' => asset('asset/img/school/outstanding-student/city/chhoeurn_sovanntheaith.png'),
        'image_43' => asset('asset/img/school/outstanding-student/city/ly_masola.png'),
    
        'image_44' => asset('asset/img/school/outstanding-student/city/sovann_raksa.png'),
        'image_45' => asset('asset/img/school/outstanding-student/city/tea_kealim.png'),
        'image_46' => asset('asset/img/school/outstanding-student/city/chan_daravatey.png'),
        'image_47' => asset('asset/img/school/outstanding-student/city/heng_pich.png'),
        'image_48' => asset('asset/img/school/outstanding-student/city/dy_salyrachana.png'),
        'image_49' => asset('asset/img/school/outstanding-student/city/keo_vanvibol.png'),
        'image_50' => asset('asset/img/school/outstanding-student/city/kong_sunmey.png'),
        'image_51' => asset('asset/img/school/outstanding-student/city/ly_pisethsovuthana.png'),
        'image_52' => asset('asset/img/school/outstanding-student/city/chan_lysa.png'),
        'image_53' => asset('asset/img/school/outstanding-student/city/samnag_puthirith.png'),
        'image_54' => asset('asset/img/school/outstanding-student/city/rith_sovatey.png'),
        'image_55' => asset('asset/img/school/outstanding-student/city/samnag_puthirith.png'),
        'image_56' => asset('asset/img/school/outstanding-student/city/koy_panady.png'),
        'image_57' => asset('asset/img/school/outstanding-student/city/so_narita.png'),
        'image_58' => asset('asset/img/school/outstanding-student/city/chhun_sovannara.png'),
        'image_59' => asset('asset/img/school/outstanding-student/city/um_sokhai.png'),
        'image_60' => asset('asset/img/school/outstanding-student/city/sok_sokha.png'),
        'image_61' => asset('asset/img/school/outstanding-student/city/puth_vitou.png'),
        'image_62' => asset('asset/img/school/outstanding-student/city/sok_porchou.png'),
        'image_63' => asset('asset/img/school/outstanding-student/city/ea_kimkeang.png'),
        'image_64' => asset('asset/img/school/outstanding-student/city/lao_meychinh.png'),
        'image_65' => asset('asset/img/school/outstanding-student/city/hong_sovannara.png'),
        'image_66' => asset('asset/img/school/outstanding-student/city/chea_meyching.png'),
        'image_67' => asset('asset/img/school/outstanding-student/city/bunna_sothida.png'),
        'image_68' => asset('asset/img/school/outstanding-student/city/tan_phearon.png'),
        'image_69' => asset('asset/img/school/outstanding-student/city/kim_rithy.png'),
        'image_70' => asset('asset/img/school/outstanding-student/city/thang_seryboth.png'),
        'image_71' => asset('asset/img/school/outstanding-student/city/thean_sreymei.png'),
        'image_72' => asset('asset/img/school/outstanding-student/city/ly_monoka.png'),
    ]) !!}

@endsection
